[package]
name = "poly"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
serde = { version = "1.0", features = ["derive"]}
serde_yml = "0.0.12"
shellexpand = "3.1.0"
subprocess = "0.2.9"
